[Issue #6] Drug taking alarm
michalmobi/PatientAssistant pull request #34
Opened 2022-12-14 12:41 UTC by piotrgos45

2022-12-29 08:13 UTC, piotrgos45 commented on app/src/main/java/com/example/patientassistant/WorkingManagers/NotificationWorker.kt
> +import com.example.patientassistant.View.DrugActivity
done

2022-12-29 08:13 UTC, piotrgos45 commented on app/src/main/java/com/example/patientassistant/Objects/NotificationHandler.kt
> +    private const val CHANNEL_ID = "notification_channel_id"
done

2022-12-29 08:13 UTC, piotrgos45 commented on app/src/main/java/com/example/patientassistant/Objects/NotificationHandler.kt
> +            .setContentText("Logging your transactions daily can help you manage your finances better.")
done

2022-12-29 08:13 UTC, piotrgos45 commented on app/src/main/java/com/example/patientassistant/Objects/NotificationHandler.kt
> +            val name = "Daily Reminders"
done

2022-12-29 08:14 UTC, piotrgos45 commented on app/src/main/java/com/example/patientassistant/Objects/NotificationHandler.kt
> +            val descriptionText = "This channel sends daily reminders to add your transactions"
done

2022-12-29 08:14 UTC, piotrgos45 commented on app/src/main/java/com/example/patientassistant/View/DrugActivity.kt
> +        val currentTime = Calendar.getInstance()
done

2022-12-29 08:40 UTC, piotrgos45 commented on app/src/main/java/com/example/patientassistant/View/DrugActivity.kt
> +            TimeUnit.SECONDS
done

2022-12-29 08:40 UTC, piotrgos45 commented on app/src/main/java/com/example/patientassistant/View/DrugActivity.kt
> +        val timeToNextDose = timeNextDose - System.currentTimeMillis()/1000
done

2022-12-29 08:42 UTC, piotrgos45 commented on app/src/main/java/com/example/patientassistant/View/DrugActivity.kt
> +            allDrugFromDatabase = allDrugFromDatabase + data
done

2022-12-29 08:42 UTC, piotrgos45 commented on app/src/main/java/com/example/patientassistant/View/DrugActivity.kt
> +                break
It was for tests, I forgot to remove this :D

2022-12-30 08:52 UTC, kozych requested changes
Cases when drug was edited or deleted from database should also be covered

2022-12-30 08:52 UTC, kozych commented on app/src/main/java/com/example/patientassistant/View/DrugActivity.kt
> +        val timeToNextDose = timeNextDose - System.currentTimeMillis()
The name of this function says nothing about starting a worker. Make it more self-descriptive

2022-12-30 08:52 UTC, kozych commented on app/src/main/java/com/example/patientassistant/View/MainActivity.kt
> +        startActivity(intent)
This should be here only for testing purposes. Please remove this

2022-12-30 08:52 UTC, kozych commented on app/src/main/java/com/example/patientassistant/Objects/NotificationHandler.kt
> +            .setContentText("It's time to take your drug!")
Include drug name and dose in content

2022-12-30 08:52 UTC, kozych commented on app/src/main/java/com/example/patientassistant/Objects/NotificationHandler.kt
> +        val intent = Intent(context, MainActivity::class.java).apply {
I would suggest launching DrugActivity when tapped

2022-12-30 08:52 UTC, kozych commented on app/src/main/java/com/example/patientassistant/Objects/NotificationHandler.kt
> +object NotificationHandler {
Change name to DrugNotificationHandler

2022-12-30 08:52 UTC, kozych commented on app/src/main/java/com/example/patientassistant/View/DrugActivity.kt
> +            }
What happens on adding new drug? Observer iterates for every drug in database, not only freshly added drug. checkHowMuchTimePassedAfterLastDose will be executed also for already existing drugs, doubling workers

2022-12-30 08:52 UTC, kozych commented on app/src/main/java/com/example/patientassistant/View/DrugActivity.kt
> +            .enqueue(
use enqueueUniquePeriodicWork instead

2022-12-30 08:53 UTC, kozych commented
Please squash commits into one

2022-12-30 17:37 UTC, piotrgos45 commented on app/src/main/java/com/example/patientassistant/View/DrugActivity.kt
> +        val timeToNextDose = timeNextDose - System.currentTimeMillis()
done

2022-12-30 17:37 UTC, piotrgos45 commented on app/src/main/java/com/example/patientassistant/View/MainActivity.kt
> +        startActivity(intent)
done

2022-12-30 17:39 UTC, piotrgos45 commented on app/src/main/java/com/example/patientassistant/Objects/NotificationHandler.kt
> +        val intent = Intent(context, MainActivity::class.java).apply {
done

2022-12-30 17:42 UTC, piotrgos45 commented on app/src/main/java/com/example/patientassistant/Objects/NotificationHandler.kt
> +object NotificationHandler {
done

2022-12-30 17:50 UTC, piotrgos45 commented on app/src/main/java/com/example/patientassistant/View/DrugActivity.kt
> +            .enqueue(
done

2022-12-30 17:58 UTC, piotrgos45 commented
I have already pushed a portion of the fixes now, I will do the rest next week

2023-01-03 10:00 UTC, kozych reviewed
Also please squash commits into one

2023-01-03 11:56 UTC, piotrgos45 commented on app/src/main/java/com/example/patientassistant/Objects/DrugNotificationHandler.kt
> +            .setContentText("It's time to take your drug!")
Done

2023-01-03 12:00 UTC, piotrgos45 commented on app/src/main/java/com/example/patientassistant/Objects/DrugNotificationHandler.kt
> +            notify(1, builder.build())
done

2023-01-03 12:03 UTC, piotrgos45 commented on app/src/main/java/com/example/patientassistant/Objects/DrugNotificationHandler.kt
> +            val descriptionText = "This channel sends reminders to take your drug"
done

2023-01-03 12:50 UTC, AlicjaKowalska commented on app/src/main/java/com/example/patientassistant/Handlers/DrugNotificationHandler.kt
> +            context, 0, intent,
Please use unique requestCode  so that it will be possible to differentiate between different requests and handle the results correctly.

2023-01-03 12:50 UTC, AlicjaKowalska commented on app/src/main/java/com/example/patientassistant/Handlers/DrugNotificationHandler.kt
> +            .setSmallIcon(R.mipmap.ic_launcher_round)
I suggest using drug.xml drawable

2023-01-03 12:50 UTC, AlicjaKowalska commented on app/src/main/java/com/example/patientassistant/Repository/DrugRepository.kt
> +        drugNotificationHandler.stopNotificationTakingNextDose(context, drug)
Please cover a case when all drugs are deleted also.

2023-01-03 12:50 UTC, AlicjaKowalska commented on app/src/main/java/com/example/patientassistant/Model/Drug.kt
> +java.io.Serializable {
What is java.io.Serializable used for?

2023-01-03 13:18 UTC, piotrgos45 commented on app/src/main/java/com/example/patientassistant/Model/Drug.kt
> +java.io.Serializable {
I was testing passing object to function, I forgot to remove this.

2023-01-03 14:20 UTC, AlicjaKowalska commented on app/src/main/java/com/example/patientassistant/workers/NotificationWorker.kt
> +                if (drugId != null) {
This can be done in one conditional statement.

2023-01-05 12:43 UTC, AlicjaKowalska commented on app/src/main/java/com/example/patientassistant/PatientApplication.kt
> +    val appointmentRepository by lazy { AppointmentRepository(database.getAppointmentDao()) }
Here should be "AppointmentRepository(this, database.getAppointmentDao())" as it is on the main branch

2023-01-09 08:34 UTC, kozych approved these changes
Looks good to me. Apply Alicja's fixes

2023-01-09 08:58 UTC, piotrgos45 commented on app/src/main/java/com/example/patientassistant/PatientApplication.kt
> +    val appointmentRepository by lazy { AppointmentRepository(database.getAppointmentDao()) }
done

2023-01-09 13:16 UTC, AlicjaKowalska approved these changes

2023-01-09 13:57 UTC, michalmobi requested changes

2023-01-09 13:57 UTC, michalmobi commented on app/src/main/java/com/example/patientassistant/workers/NotificationWorker.kt
> +        val drugName = inputData.getString("drug_name")
move `drug_name` etc to some constant

2023-01-09 13:57 UTC, michalmobi commented on app/src/main/java/com/example/patientassistant/Handlers/DrugNotificationHandler.kt
> +            .putString("drug_name", drug.name)
move `drug_name` etc to some constant

2023-01-10 08:26 UTC, piotrgos45 commented on app/src/main/java/com/example/patientassistant/workers/NotificationWorker.kt
> +        val drugName = inputData.getString("drug_name")
done

2023-01-10 08:26 UTC, piotrgos45 commented on app/src/main/java/com/example/patientassistant/Handlers/DrugNotificationHandler.kt
> +            .putString("drug_name", drug.name)
done

2023-01-10 08:59 UTC, michalmobi requested changes

2023-01-10 08:59 UTC, michalmobi commented on app/build.gradle
> +    def work_version = "2.7.1"
please move version number to `ext`  in `build.gradle`  and use it like most of the other dependencies here, for example:
`implementation "androidx.appcompat:appcompat:$rootProject.appCompatVersion"`

2023-01-10 08:59 UTC, michalmobi commented on app/src/main/java/com/example/patientassistant/workers/NotificationWorker.kt
> +            drugNotificationHandler.createReminderNotification(
add Timber log here

2023-01-10 08:59 UTC, michalmobi commented on app/src/main/java/com/example/patientassistant/workers/NotificationWorker.kt
> +        if (drugName != null && drugDose != null && drugId != null) {
add Timber log if any of these values is null

2023-01-10 10:41 UTC, piotrgos45 commented on app/build.gradle
> +    def work_version = "2.7.1"
done

2023-01-10 10:45 UTC, piotrgos45 commented on app/src/main/java/com/example/patientassistant/workers/NotificationWorker.kt
> +        if (drugName != null && drugDose != null && drugId != null) {
Please check if I have done this correctly

2023-01-10 18:33 UTC, michalmobi approved these changes

2023-01-11 08:36 UTC, merged