[Issue #10] Map of pharmacies and medical facilities draft
michalmobi/PatientAssistant pull request #37
Opened 2022-12-27 09:23 UTC by kozych

2023-01-02 13:18 UTC, AlicjaKowalska reviewed
You should also cover a case when the location is turned off. I also suggest applying some ProgressBar when loading the map because it won't load so fast every time, it could load slow when the user's connection is weak.

2023-01-02 13:18 UTC, AlicjaKowalska commented on app/src/main/res/layout/activity_map.xml
> +        <Button
I suggest using Chips in a ChipGroup here instead of regular Buttons. Also filtering Button is missing which would make the Chips visible.

2023-01-09 08:30 UTC, kozych commented on app/src/main/res/layout/activity_map.xml
> +        <Button
done

2023-01-09 12:49 UTC, AlicjaKowalska approved these changes
It seems to be no problem with displaying map when having bad connection but there's a problem finding places when having bad internet connection. We should solve this issue in another PR.

2023-01-10 09:15 UTC, piotrgos45 approved these changes

2023-01-10 09:34 UTC, michalmobi requested changes

2023-01-10 09:34 UTC, michalmobi commented on app/src/main/java/com/example/patientassistant/Fragment/MapHelperFragment.kt
> +            if (isChecked) {
create a separate function which will create a listener and pass parameter MapActivity.HOSPITAL or MapActivity.PHARMACY etc to it.

2023-01-10 10:51 UTC, kozych commented on app/src/main/java/com/example/patientassistant/Fragment/MapHelperFragment.kt
> +            if (isChecked) {
done

2023-01-10 18:40 UTC, michalmobi requested changes

2023-01-10 18:40 UTC, michalmobi commented on app/src/main/java/com/example/patientassistant/Fragment/MapHelperFragment.kt
> +                addressList = geocoder.getFromLocationName(location, 1)
add comment about `1`

2023-01-10 18:40 UTC, michalmobi commented on app/src/main/java/com/example/patientassistant/Fragment/MapHelperFragment.kt
> +                e.printStackTrace()
use `Timber.e("exception during location search", e)` instead of `printStackTrace`

2023-01-10 18:40 UTC, michalmobi commented on app/src/main/java/com/example/patientassistant/Fragment/MapHelperFragment.kt
> +                e.printStackTrace()
use `Timber.e("exception when getting place", e)` instead of `printStackTrace`

2023-01-10 18:40 UTC, michalmobi commented on app/src/main/java/com/example/patientassistant/Fragment/MapHelperFragment.kt
> +        }, { error -> error.printStackTrace() })
same here

2023-01-11 08:43 UTC, kozych commented on app/src/main/java/com/example/patientassistant/Fragment/MapHelperFragment.kt
> +                addressList = geocoder.getFromLocationName(location, 1)
done

2023-01-11 08:44 UTC, kozych commented on app/src/main/java/com/example/patientassistant/Fragment/MapHelperFragment.kt
> +                e.printStackTrace()
done

2023-01-11 09:38 UTC, michalmobi approved these changes

2023-01-11 11:04 UTC, merged