[issue #26] Appointment details and edit functionality
michalmobi/PatientAssistant pull request #50
Opened 2023-01-12 14:17 UTC by piotrgos45

2023-01-13 09:00 UTC, kozych requested changes
User is not able to add new appointment from app level. Please implement this

2023-01-13 09:00 UTC, kozych commented on app/src/main/res/values/strings.xml
> +    <string name="CANCEL">CANCEL</string>
Please use the cancel string above

2023-01-13 09:00 UTC, kozych commented on app/src/main/java/com/example/patientassistant/View/MedicalAppointmentFormActivity.kt
> +            startActivity(intent)
Don't start new activity every time you want to exit "edit mode". Just edit existing activity

2023-01-13 09:00 UTC, kozych commented on app/src/main/java/com/example/patientassistant/View/MedicalAppointmentFormActivity.kt
> +        binding.buttonEdit.text = R.string.CANCEL.toString()
use `binding.buttonEdit.setText(R.string.cancel)` instead ;)
![image](https://user-images.githubusercontent.com/117084700/212274482-02a11039-ca8e-4a07-93f4-e0d030230728.png)

2023-01-13 09:00 UTC, kozych commented on app/src/main/java/com/example/patientassistant/View/MedicalAppointmentFormActivity.kt
> +                startActivity(Intent(this, MedicalAppointmentsActivity::class.java))
Don't start new activity. This activity stays in history and can be accessed by pressing back button if you do so. Use `finish()` instead

2023-01-13 09:00 UTC, kozych commented on app/src/main/java/com/example/patientassistant/View/MedicalAppointmentFormActivity.kt
> +                    )
Activity with already deleted appointment could be accessed if you start new activity here. Use `finish()` instead

2023-01-13 09:00 UTC, kozych commented on app/src/main/java/com/example/patientassistant/View/MedicalAppointmentFormActivity.kt
> +            intent.getSerializableExtra("current_appointment", Appointment::class.java)!!
Using non-null assert call here has some implications. `appointment` will never be null so next if will always go into else. This create issues with creating activity for creating new appointment

2023-01-13 09:00 UTC, kozych commented on app/src/main/java/com/example/patientassistant/View/MedicalAppointmentFormActivity.kt
> +            intent.getSerializableExtra("current_appointment", Appointment::class.java)!!
I strongly suggest removing `!!`

2023-01-13 09:00 UTC, kozych commented on app/src/main/java/com/example/patientassistant/View/MedicalAppointmentFormActivity.kt
> +import android.util.Log
Unused import

2023-01-13 09:00 UTC, kozych commented on app/src/main/java/com/example/patientassistant/View/MedicalAppointmentDetailEditForm.kt
> +class MedicalAppointmentDetailEditForm : AppCompatActivity() {
Unused class. Please remove this file

2023-01-13 09:00 UTC, kozych commented on app/src/main/res/layout/activity_medical_appointment_detail_edit_form.xml
> +    >
Please delete this file

2023-01-13 09:00 UTC, kozych commented on app/src/main/AndroidManifest.xml
> +        </activity>
We do need this activity. Please remove this

2023-01-13 09:00 UTC, kozych commented on app/src/main/java/com/example/patientassistant/View/MainActivity.kt
> +        val appointmentAdapter = AppointmentAdapter() {Appointment ->}
User should be able to go to details view also in home screen. Please implement this

2023-01-13 09:00 UTC, kozych commented on app/src/main/java/com/example/patientassistant/View/MedicalAppointmentsActivity.kt
> +
please remove this line

2023-01-13 09:00 UTC, kozych commented on app/src/main/java/com/example/patientassistant/View/MedicalAppointmentFormActivity.kt
> +
please remove this line

2023-01-13 09:20 UTC, kozych commented on app/src/main/java/com/example/patientassistant/View/MedicalAppointmentFormActivity.kt
> +            intent.getSerializableExtra("current_appointment", Appointment::class.java)!!
For testing scenario - create new activity without passing appointment and see what happens. 

https://www.baeldung.com/kotlin/not-null-assertion

2023-01-16 09:02 UTC, piotrgos45 commented on app/src/main/res/values/strings.xml
> +    <string name="CANCEL">CANCEL</string>
done

2023-01-16 09:34 UTC, piotrgos45 commented on app/src/main/java/com/example/patientassistant/View/MedicalAppointmentFormActivity.kt
> +        binding.buttonEdit.text = R.string.CANCEL.toString()
done

2023-01-18 08:31 UTC, kozych commented
App is crashing when trying to edit appointment
![image](https://user-images.githubusercontent.com/117084700/213121848-cb045f18-970c-4724-97ab-342db82288f6.png)

2023-01-18 10:52 UTC, piotrgos45 commented
> App is crashing when trying to edit appointment ![image](https://user-images.githubusercontent.com/117084700/213121848-cb045f18-970c-4724-97ab-342db82288f6.png)

It is, because Notification require an small icon. AppointmentNotificationsHandler and CommonAppointmentNotifications doesn't include this. I don't know if I should fix it within this task or we should create new task for it.

2023-01-18 13:00 UTC, piotrgos45 commented
> > App is crashing when trying to edit appointment ![image](https://user-images.githubusercontent.com/117084700/213121848-cb045f18-970c-4724-97ab-342db82288f6.png)
> 
> It is, because Notification require an small icon. AppointmentNotificationsHandler and CommonAppointmentNotifications doesn't include this. I don't know if I should fix it within this task or we should create new task for it.

Created new task for it: https://github.com/michalmobi/PatientAssistant/pull/62

2023-01-19 09:19 UTC, kozych approved these changes

2023-01-19 13:57 UTC, AlicjaKowalska commented on app/src/main/java/com/example/patientassistant/view/MedicalAppointmentFormActivity.kt
> +                val newAppointment = Appointment(
This object is not used anywhere.

2023-01-19 13:57 UTC, AlicjaKowalska commented on app/src/main/java/com/example/patientassistant/adapters/AppointmentAdapter.kt
>                  currentAppointment.day.toString() + "." + currentAppointment.month.toString() + "." + currentAppointment.year.toString()
Month and day also need a "0" before single digit, also month needs to be +1. It'd be nice if you could do that too :)

2023-01-19 14:48 UTC, piotrgos45 commented on app/src/main/java/com/example/patientassistant/adapters/AppointmentAdapter.kt
>                  currentAppointment.day.toString() + "." + currentAppointment.month.toString() + "." + currentAppointment.year.toString()
done

2023-01-19 15:00 UTC, AlicjaKowalska approved these changes

2023-01-20 09:19 UTC, michalmobi commented
@kozych @piotrgos45 please don't insert screenshots with errors, just paste the copied text. Example:

>     java.lang.NullPointerException
            at com.example.amosref.middleproject.ContactFromList.onListItemClick(ContactFromList.java:56)
            at android.app.ListActivity$2.onItemClick(ListActivity.java:319)
            at android.widget.AdapterView.performItemClick(AdapterView.java:299)
            at android.widget.AbsListView.performItemClick(AbsListView.java:1153)
            at android.widget.AbsListView$PerformClick.run(AbsListView.java:3065)
            at android.widget.AbsListView$3.run(AbsListView.java:4031)
            at android.os.Handler.handleCallback(Handler.java:808)
            at android.os.Handler.dispatchMessage(Handler.java:103)
            at android.os.Looper.loop(Looper.java:193)

2023-01-20 09:26 UTC, michalmobi requested changes

2023-01-20 09:26 UTC, michalmobi commented on app/src/main/java/com/example/patientassistant/view/MedicalAppointmentFormActivity.kt
> +    private fun makeEditTextEditable() {
instead of `binding.editTextTitle.isEnabled = true` use:
`with (binding) {
    editTextTitle.isEnabled = true
...
`

2023-01-20 09:26 UTC, michalmobi commented on app/src/main/java/com/example/patientassistant/view/MedicalAppointmentsActivity.kt
> +            intent.putExtra("current_appointment", it)
define `current_appointment` in class companion object val

2023-01-20 10:45 UTC, piotrgos45 commented on app/src/main/java/com/example/patientassistant/view/MedicalAppointmentFormActivity.kt
> +    private fun makeEditTextEditable() {
done

2023-01-20 10:56 UTC, piotrgos45 commented on app/src/main/res/layout/activity_medical_appointments.xml
> +        android:clickable="true"
I remove it :D

2023-01-20 11:20 UTC, michalmobi approved these changes

2023-01-20 12:06 UTC, merged