[Issue #45] Setting Screen
michalmobi/PatientAssistant pull request #60
Opened 2023-01-18 10:11 UTC by kozych

Added setting activity with options
Enable/disable notifications for medicament reminders
Enable/disable notifications for medical appointments reminders
Enable/disable night mode
ask again for permissions

2023-01-19 12:32 UTC, piotrgos45 commented
In settings screen, the back arrow (on left top corner) doesn't work.

2023-01-19 12:51 UTC, AlicjaKowalska commented on app/src/main/java/com/example/patientassistant/view/SettingsActivity.kt
> +                    AppCompatDelegate.setDefaultNightMode(AppCompatDelegate.MODE_NIGHT_YES)
Night mode doesn't work after destroying the app.

2023-01-24 07:54 UTC, kozych commented on app/src/main/java/com/example/patientassistant/view/SettingsActivity.kt
> +                    AppCompatDelegate.setDefaultNightMode(AppCompatDelegate.MODE_NIGHT_YES)
done

2023-01-24 07:54 UTC, kozych commented
> In settings screen, the back arrow (on left top corner) doesn't work.

done

2023-01-24 09:29 UTC, AlicjaKowalska approved these changes

2023-01-24 20:14 UTC, piotrgos45 approved these changes

2023-01-25 10:07 UTC, michalmobi requested changes

2023-01-26 07:48 UTC, kozych commented on app/src/main/java/com/example/patientassistant/view/SettingsActivity.kt
> +                            settingsActivity,
I think it is better now

2023-01-26 08:41 UTC, michalmobi approved these changes

2023-01-26 09:19 UTC, merged