[Issue 79] Add back buttons to screens: drugs, appointments
michalmobi/PatientAssistant pull request #80
Opened 2023-01-31 09:47 UTC by kozych

added back buttons to drugform and appointmentform

2023-02-01 11:37 UTC, AlicjaKowalska approved these changes
LGTM

2023-02-01 13:09 UTC, piotrgos45 approved these changes

2023-02-02 09:13 UTC, michalmobi requested changes

2023-02-02 10:30 UTC, kozych commented on app/src/main/java/com/example/patientassistant/view/MedicalAppointmentFormActivity.kt
> +            when (menuItem.itemId) {
good point, done

2023-02-02 10:31 UTC, kozych commented on app/src/main/java/com/example/patientassistant/view/MedicalAppointmentFormActivity.kt
> +                    Log.i("Menu", "Home selected")
done

2023-02-02 11:31 UTC, michalmobi approved these changes

2023-02-02 11:45 UTC, merged